version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
  db:
    restart: always
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Nazran@123
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

