# Server Configuration
server:
  port: 5000
  error:
    include-stacktrace: always
  compression:
    enabled: true
#  address: 0.0.0.0


# Spring Configuration
spring:
  application:
    name: rbtsb-service

  # Database Configuration
  datasource:

    # docker local
#    url: jdbc:sqlserver://localhost:1433;databaseName=rbtsb;encrypt=true;trustServerCertificate=true;
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    username: sa
#    password: Nazran@123
    # local
    url: jdbc:mysql://localhost:3306/rbtsb
    username: root
    password: root

    driver-class-name: com.mysql.cj.jdbc.Driver

    # Hikari Configuration
    hikari:
      minimum-idle: 1
      maximum-pool-size: 15
      idle-timeout: 30000
      pool-name: SpringBootJPAHikariCP
      max-lifetime: 2000000
      connection-timeout: 30000

  # JPA Configuration
  jpa:
    # Properties
    properties:
      # Hibernate Properties
      # The SQL dialect makes Hibernate generate better SQL for the chosen database
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        dialect: org.hibernate.dialect.SQLServer2012Dialect
        naming:
          implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show_sql: true
        format_sql: true
        use_sql: true
        shutdown_on_session_factory_close: false
        connection:
          characterEncoding: utf-8
          CharSet: utf-8
          useUnicode: true
          legacy_limit_handler: true

    # Hibernate
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  # Servlet Configuration
  servlet:
    multipart:
      enabled: true
      location: /tmp
      max-file-size: 512MB
      max-request-size: 512MB
      resolve-lazily: false

  # Redis Configuration
  redis:
    host: localhost
    port: 6379
    connect-timeout: 21600


# Management Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"

cityLinkService: ${cityLinkServiceBaseUrl:https://www.citylinkexpress.com/}
#ftpFileUploadPath: /rbtsb-service
